<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Vite Asset Path
    |--------------------------------------------------------------------------
    |
    | This value controls the public path where Vite assets will be served
    | from. This path is relative to the public directory.
    |
    */
    'asset_path' => 'build',

    /*
    |--------------------------------------------------------------------------
    | Hot File Path
    |--------------------------------------------------------------------------
    |
    | When you run `npm run dev`, Vite generates a `hot` file. This file
    | contains the URL to your Vite dev server. This file is used to
    | determine if Vite is running in dev mode.
    |
    */
    'hot_file' => public_path('hot'),

    /*
    |--------------------------------------------------------------------------
    | Build Directory
    |--------------------------------------------------------------------------
    |
    | This value determines where the compiled assets will be placed. This
    | is relative to the public directory.
    |
    */
    'build_directory' => 'build',

    /*
    |--------------------------------------------------------------------------
    | Manifest Filename
    |--------------------------------------------------------------------------
    |
    | The filename of the Vite manifest file. This file is generated by
    | Vite when you run `npm run build`.
    |
    */
    'manifest_filename' => 'manifest.json',
];